development:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/developmentyolo.sqlite3
test:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/testyolo.sqlite3

production:
  adapter: postgresql
  database: alpha_blog_production
  pool: 5
  timeout: 5000