development:
  adapter: postgresql
  database: alpha_blog_development
  pool: 5
  timeout: 5000
  # adapter: sqlite3
  
test:
  adapter: postgresql
  database: alpha_blog_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: alpha_blog_production
  pool: 5
  timeout: 5000
  